apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: agri-afta

build:
  artifacts:
    - image: agri-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: agri-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml