apiVersion: skaffold/v4beta6
kind: Config

metadata:
  name: agri-afta

build:
  artifacts:
    - image: agri-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: agri-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/backend-deploy.yaml
      - k8s/backend-svc.yaml
      - k8s/frontend-deploy.yaml
      - k8s/frontend-svc.yaml
      - k8s/prometheus-configmap.yaml
      - k8s/prometheus-deploy.yaml
      - k8s/grafana-deploy.yaml
      - k8s/mlflow-deploy.yaml
      - k8s/retrain-cronjob.yaml
