name: dotnet-workflow6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------------------------------
    # 1. CHECKOUT CODE
    # -------------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # -------------------------------------------------------
    # 2. PYTHON BACKEND SETUP + TEST
    # -------------------------------------------------------
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Backend sanity test
      run: |
        python - <<EOF
        import sys
        sys.path.insert(0, 'backend')
        from model_loader import ModelWrapper
        print("✓ Python backend OK")
        EOF
    # -------------------------------------------------------
    # 3. .NET CORE GATEWAY SETUP
    # -------------------------------------------------------
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Restore .NET dependencies
      working-directory: agri-gateway
      run: dotnet restore

    - name: Build .NET Gateway
      working-directory: agri-gateway
      run: dotnet build --configuration Release --no-restore

    # -------------------------------------------------------
    # 4. LOGIN TO DOCKERHUB
    # -------------------------------------------------------
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # -------------------------------------------------------
    # 5. FREE UP DISK SPACE (KEPT)
    # -------------------------------------------------------
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/lib/android
        docker system prune -af --volumes
        df -h
    # -------------------------------------------------------
    # 6. DOCKER BUILDX
    # -------------------------------------------------------
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # -------------------------------------------------------
    # 7. BUILD & PUSH PYTHON BACKEND IMAGE
    # -------------------------------------------------------
    - name: Build backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/agri-backend:latest
        platforms: linux/amd64, linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # -------------------------------------------------------
    # 8. BUILD & PUSH FRONTEND IMAGE
    # -------------------------------------------------------
    - name: Build frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/agri-frontend:latest
        platforms: linux/amd64, linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # -------------------------------------------------------
    # 9. BUILD & PUSH .NET GATEWAY IMAGE
    # -------------------------------------------------------
    - name: Build gateway Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./agri-gateway
        file: ./agri-gateway/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/agri-gateway:latest
        platforms: linux/amd64, linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # -------------------------------------------------------
    # 10. SET UP KUBECTL
    # -------------------------------------------------------
    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: v1.29.0

    # -------------------------------------------------------
    # 11. CONFIGURE KUBECONFIG
    # -------------------------------------------------------
    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" > ~/.kube/config
    # -------------------------------------------------------
    # 12. DEPLOY TO KUBERNETES
    # -------------------------------------------------------
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        kubectl rollout restart deployment agri-backend || true
        kubectl rollout restart deployment agri-frontend || true
        kubectl rollout restart deployment agri-gateway || true
    # -------------------------------------------------------
    # 13. VERIFY DEPLOYMENT
    # -------------------------------------------------------
    - name: Verify pods
      run: kubectl get pods

    # -------------------------------------------------------
    # 14. DEPLOYMENT MESSAGE
    # -------------------------------------------------------
    - name: Deployment completed
      run: |
        echo "====================================="
        echo "✅ CI/CD Pipeline Completed!"
        echo "====================================="
        echo "Images pushed:"
        echo " - agri-backend"
        echo " - agri-frontend"
        echo " - agri-gateway"
        echo "Kubernetes deployment updated"