# -------------------------------
# 1. BUILD STAGE
# -------------------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy csproj and restore
COPY *.csproj ./
RUN dotnet restore

# Copy rest of the source code
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# -------------------------------
# 2. RUNTIME STAGE
# -------------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

# ASP.NET Core default port
EXPOSE 80

ENTRYPOINT ["dotnet", "agri-gateway.dll"]
